# Generated by Django 4.2.5 on 2024-11-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='id_req_doc',
            field=models.CharField(default=1, help_text='Identificador del requisito', max_length=50, verbose_name='ID del requisito en el documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Archivo del documento de requisitos', null=True, upload_to='documents/'),
        ),
    ]
