# Generated by Django 4.2.5 on 2024-11-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_document_content_text_requirement_id_req_doc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content_text',
            new_name='texto_manual',
        ),
    ]
