# Generated by Django 4.2.5 on 2024-11-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_rename_content_text_document_texto_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archivo_resaltado',
            field=models.FileField(blank=True, help_text='Archivo del documento de requisitos resaltado', null=True, upload_to='documentos_resaltados/'),
        ),
    ]
