# Generated by Django 4.2.5 on 2024-11-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_document_archivo_resaltado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiguity',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='ambiguity',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ambiguity',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='ambiguity',
            name='type',
        ),
        migrations.RemoveField(
            model_name='disambiguationsuggestion',
            name='justification',
        ),
    ]
