# Generated by Django 4.2.5 on 2024-11-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_remove_ambiguity_impact_remove_ambiguity_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiguity',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='id_req_doc',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ambiguity',
            name='description',
            field=models.TextField(help_text='Palabras o frases que causan la ambigüedad', null=True, verbose_name='Palabras clave ambiguas'),
        ),
    ]
