# Generated by Django 4.2.5 on 2024-11-05 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiguity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Tipo de ambigüedad detectada (e.g., léxica, referencial)', max_length=50, verbose_name='Tipo de ambigüedad')),
                ('description', models.TextField(help_text='Descripción de la ambigüedad detectada', verbose_name='Descripción de la ambigüedad')),
                ('location', models.CharField(help_text='Posición en el texto o en el documento', max_length=100, verbose_name='Ubicación en el requisito')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Archivo del documento de requisitos', upload_to='documents/')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del archivo original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Texto completo del requisito ingresado', verbose_name='Texto del requisito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='modelo.document')),
            ],
        ),
        migrations.CreateModel(
            name='DisambiguationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField(help_text='Texto que propone una solución para la ambigüedad', verbose_name='Sugerencia de desambiguación')),
                ('ambiguity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='modelo.ambiguity')),
            ],
        ),
        migrations.AddField(
            model_name='ambiguity',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiguities', to='modelo.requirement'),
        ),
    ]
