# Generated by Django 4.2.5 on 2024-11-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_document_user_requirement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiguity',
            name='impact',
            field=models.TextField(default=1, help_text='Descripción del posible impacto en el desarrollo', verbose_name='Impacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambiguity',
            name='keywords',
            field=models.JSONField(help_text='Palabras o frases que causan la ambigüedad', null=True, verbose_name='Palabras clave ambiguas'),
        ),
        migrations.AddField(
            model_name='ambiguity',
            name='severity',
            field=models.CharField(default=1, help_text='Gravedad de la ambigüedad', max_length=50, verbose_name='Gravedad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disambiguationsuggestion',
            name='justification',
            field=models.TextField(default=1, help_text='Explicación de por qué la propuesta resuelve la ambigüedad', verbose_name='Justificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='tipo',
            field=models.CharField(default=1, help_text='Funcional o No Funcional', max_length=50, verbose_name='Tipo de requisito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambiguity',
            name='type',
            field=models.CharField(help_text='Tipo de ambigüedad detectada', max_length=50, verbose_name='Tipo de ambigüedad'),
        ),
    ]
