# Generated by Django 4.2.5 on 2024-11-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_remove_document_user_remove_requirement_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disambiguationsuggestion',
            name='ambiguity',
        ),
        migrations.RemoveField(
            model_name='document',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='document',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Ambiguity',
        ),
        migrations.DeleteModel(
            name='DisambiguationSuggestion',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
